#
# GNUmakefile
# Shlomi Fish, 2024-04-04 20:04
#

ROOT_SOURCE_DIR = .
PERL = perl
README = $(ROOT_SOURCE_DIR)/README.md

all: $(README)

$(README): $(ROOT_SOURCE_DIR)/validate-your-html.docbook5.xml
	( set -e -x ; printf "%s\\n\\n" "**WARNING!!** This file is now generated by $(MAKE) . DO NOT MODIFY directly!" && ( pandoc -f docbook -t gfm --columns=1000 < $< | $(PERL) -lp $(ROOT_SOURCE_DIR)/bin/reindent-pandoc-gh-flavored-markdown-output-to-4-spaces.pl ) ) > $@

# vim:ft=make
#
